
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/59985e8ef39dba82442f034a372367363080462f_flag_if_job_task_fail
test $? -ne 0 && exit 1



***REMOVED*** source /opt/intel/oneapi/setvars.sh; ***REMOVED*** 




cd $REMOTE_ROOT
cd sys-0004-0001
test $? -ne 0 && exit 1
if [ ! -f 13c8d949d8d3a123f2b1390c172337b82e865508_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 13c8d949d8d3a123f2b1390c172337b82e865508_task_tag_finished; else echo 1 > $REMOTE_ROOT/59985e8ef39dba82442f034a372367363080462f_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 59985e8ef39dba82442f034a372367363080462f_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 59985e8ef39dba82442f034a372367363080462f_job_tag_finished; else exit 1;fi

