
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/0933adf99e4174f59420eb733d5744bab817f18a_flag_if_job_task_fail
test $? -ne 0 && exit 1



{ source /opt/intel/oneapi/setvars.sh; } 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000019
test $? -ne 0 && exit 1
if [ ! -f 2602fbd74b2006cc905d1857e303072b8893935b_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 2602fbd74b2006cc905d1857e303072b8893935b_task_tag_finished; else echo 1 > $REMOTE_ROOT/0933adf99e4174f59420eb733d5744bab817f18a_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 0933adf99e4174f59420eb733d5744bab817f18a_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 0933adf99e4174f59420eb733d5744bab817f18a_job_tag_finished; else exit 1;fi

