
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/161d108ff19ad414b409d5478eded6c74398cd81_flag_if_job_task_fail
test $? -ne 0 && exit 1



***REMOVED*** source /opt/intel/oneapi/setvars.sh; ***REMOVED*** 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000013
test $? -ne 0 && exit 1
if [ ! -f 5f0dd69cfc18f70828313b8bb7e936cd1a532ca6_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 5f0dd69cfc18f70828313b8bb7e936cd1a532ca6_task_tag_finished; else echo 1 > $REMOTE_ROOT/161d108ff19ad414b409d5478eded6c74398cd81_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 161d108ff19ad414b409d5478eded6c74398cd81_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 161d108ff19ad414b409d5478eded6c74398cd81_job_tag_finished; else exit 1;fi

