
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/3f4959bd42cec29ffc1ecd7a8fe6eab51e84f6a2_flag_if_job_task_fail
test $? -ne 0 && exit 1



***REMOVED*** source /opt/intel/oneapi/setvars.sh; ***REMOVED*** 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000010
test $? -ne 0 && exit 1
if [ ! -f 72c54c0674a4d23385af3f926236d014a70e5582_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 72c54c0674a4d23385af3f926236d014a70e5582_task_tag_finished; else echo 1 > $REMOTE_ROOT/3f4959bd42cec29ffc1ecd7a8fe6eab51e84f6a2_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 3f4959bd42cec29ffc1ecd7a8fe6eab51e84f6a2_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 3f4959bd42cec29ffc1ecd7a8fe6eab51e84f6a2_job_tag_finished; else exit 1;fi

