
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/40622949de6bf8347ce4ed8bffc97ed508a2e23d_flag_if_job_task_fail
test $? -ne 0 && exit 1



{ source /opt/intel/oneapi/setvars.sh; } 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000026
test $? -ne 0 && exit 1
if [ ! -f 05e8865dff6a1ee76ed5c3c467a6e0fcc2e57df3_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 05e8865dff6a1ee76ed5c3c467a6e0fcc2e57df3_task_tag_finished; else echo 1 > $REMOTE_ROOT/40622949de6bf8347ce4ed8bffc97ed508a2e23d_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 40622949de6bf8347ce4ed8bffc97ed508a2e23d_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 40622949de6bf8347ce4ed8bffc97ed508a2e23d_job_tag_finished; else exit 1;fi

