
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/43ba5ed1a1059d547829523e9740b53041f91f25_flag_if_job_task_fail
test $? -ne 0 && exit 1



***REMOVED*** source /opt/intel/oneapi/setvars.sh; ***REMOVED*** 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000008
test $? -ne 0 && exit 1
if [ ! -f a6aacab07dd9b55084386ad7040567ccbdcacc1d_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch a6aacab07dd9b55084386ad7040567ccbdcacc1d_task_tag_finished; else echo 1 > $REMOTE_ROOT/43ba5ed1a1059d547829523e9740b53041f91f25_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 43ba5ed1a1059d547829523e9740b53041f91f25_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 43ba5ed1a1059d547829523e9740b53041f91f25_job_tag_finished; else exit 1;fi

