
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/68b2e2ec9ab97e62641ed1f70520f6daa8802629_flag_if_job_task_fail
test $? -ne 0 && exit 1



{ source /opt/intel/oneapi/setvars.sh; } 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000023
test $? -ne 0 && exit 1
if [ ! -f 39e5d0a78e2071450d13a389f4f4befcebc06343_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 39e5d0a78e2071450d13a389f4f4befcebc06343_task_tag_finished; else echo 1 > $REMOTE_ROOT/68b2e2ec9ab97e62641ed1f70520f6daa8802629_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 68b2e2ec9ab97e62641ed1f70520f6daa8802629_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 68b2e2ec9ab97e62641ed1f70520f6daa8802629_job_tag_finished; else exit 1;fi

