
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/888d3e38953cfb9fa2b3fb2adbb787a77fc790a8_flag_if_job_task_fail
test $? -ne 0 && exit 1



{ source /opt/intel/oneapi/setvars.sh; } 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000005
test $? -ne 0 && exit 1
if [ ! -f 72f504fbf0d6e217524f6e1b4a5d7b2edc1fade0_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 72f504fbf0d6e217524f6e1b4a5d7b2edc1fade0_task_tag_finished; else echo 1 > $REMOTE_ROOT/888d3e38953cfb9fa2b3fb2adbb787a77fc790a8_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 888d3e38953cfb9fa2b3fb2adbb787a77fc790a8_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 888d3e38953cfb9fa2b3fb2adbb787a77fc790a8_job_tag_finished; else exit 1;fi

