
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/92e1acea80e0059c53907c787b81aa4f8ad7c347_flag_if_job_task_fail
test $? -ne 0 && exit 1



{ source /opt/intel/oneapi/setvars.sh; } 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000006
test $? -ne 0 && exit 1
if [ ! -f 45b6e49571f0f2a4a1a21377fe51ef8aaddcfb51_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 45b6e49571f0f2a4a1a21377fe51ef8aaddcfb51_task_tag_finished; else echo 1 > $REMOTE_ROOT/92e1acea80e0059c53907c787b81aa4f8ad7c347_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 92e1acea80e0059c53907c787b81aa4f8ad7c347_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 92e1acea80e0059c53907c787b81aa4f8ad7c347_job_tag_finished; else exit 1;fi

