
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/c0ac321ac245d732fc80a4027330c9a06e642ce2_flag_if_job_task_fail
test $? -ne 0 && exit 1



{ source /opt/intel/oneapi/setvars.sh; } 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000025
test $? -ne 0 && exit 1
if [ ! -f aa92ef8e5e31d25b126594697d4ca42c3cbdcf92_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch aa92ef8e5e31d25b126594697d4ca42c3cbdcf92_task_tag_finished; else echo 1 > $REMOTE_ROOT/c0ac321ac245d732fc80a4027330c9a06e642ce2_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat c0ac321ac245d732fc80a4027330c9a06e642ce2_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch c0ac321ac245d732fc80a4027330c9a06e642ce2_job_tag_finished; else exit 1;fi

