
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/c52efbae70da4ff666a58e02f429767bc1dbc960_flag_if_job_task_fail
test $? -ne 0 && exit 1



***REMOVED*** source /opt/intel/oneapi/setvars.sh; ***REMOVED*** 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000016
test $? -ne 0 && exit 1
if [ ! -f 22077883f32ecdca45ea09d1fa21ba4f1392aa78_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 22077883f32ecdca45ea09d1fa21ba4f1392aa78_task_tag_finished; else echo 1 > $REMOTE_ROOT/c52efbae70da4ff666a58e02f429767bc1dbc960_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat c52efbae70da4ff666a58e02f429767bc1dbc960_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch c52efbae70da4ff666a58e02f429767bc1dbc960_job_tag_finished; else exit 1;fi

