
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/f1998c4b2b5da3441a705ec989d8122f6f2cdf46_flag_if_job_task_fail
test $? -ne 0 && exit 1



{ source /opt/intel/oneapi/setvars.sh; } 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000017
test $? -ne 0 && exit 1
if [ ! -f 5880092ed9f96af656c9d7168c2830d64929e49d_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 5880092ed9f96af656c9d7168c2830d64929e49d_task_tag_finished; else echo 1 > $REMOTE_ROOT/f1998c4b2b5da3441a705ec989d8122f6f2cdf46_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat f1998c4b2b5da3441a705ec989d8122f6f2cdf46_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch f1998c4b2b5da3441a705ec989d8122f6f2cdf46_job_tag_finished; else exit 1;fi

