
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/f400816d669e512cf7acb2dc5445846048dea56b_flag_if_job_task_fail
test $? -ne 0 && exit 1



***REMOVED*** source /opt/intel/oneapi/setvars.sh; ***REMOVED*** 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000022
test $? -ne 0 && exit 1
if [ ! -f 667450c58fd62c9bc59e424e61a75f6f27a94fd5_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 667450c58fd62c9bc59e424e61a75f6f27a94fd5_task_tag_finished; else echo 1 > $REMOTE_ROOT/f400816d669e512cf7acb2dc5445846048dea56b_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat f400816d669e512cf7acb2dc5445846048dea56b_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch f400816d669e512cf7acb2dc5445846048dea56b_job_tag_finished; else exit 1;fi

